table Factions
	lineageTag: 29cf617a-ffbd-494a-9649-aa8e449bb7f0

	column Macrofaction
		dataType: string
		lineageTag: 25181ba5-f6a3-4439-8b57-1bbd8684f517
		summarizeBy: none
		sourceColumn: Macrofaction

		annotation SummarizationSetBy = Automatic

	column Faction
		dataType: string
		lineageTag: 1ad90d5e-19d2-456a-a71e-b4af8c92bf07
		summarizeBy: none
		sourceColumn: Faction

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition Factions = m
		mode: import
		queryGroup: '00 Utilities\00.02 Support Tables'
		source =
				let
				    Source = #"supportTables-stg",
				    Data = Source{1}[Data],
				    #"Split Column by Delimiter" = Table.SplitColumn(Data, "Column1", Splitter.SplitTextByDelimiter("~", QuoteStyle.Csv), {"Column1.1", "Column1.2"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Split Column by Delimiter", [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

