table Factions
	lineageTag: 29cf617a-ffbd-494a-9649-aa8e449bb7f0

	column Macrofaction
		dataType: string
		lineageTag: 25181ba5-f6a3-4439-8b57-1bbd8684f517
		summarizeBy: none
		sourceColumn: Macrofaction

		annotation SummarizationSetBy = Automatic

	column Faction
		dataType: string
		lineageTag: 1ad90d5e-19d2-456a-a71e-b4af8c92bf07
		summarizeBy: none
		sourceColumn: Faction

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition Factions = m
		mode: import
		queryGroup: '00 Utilities\00.03 FromGitHub'
		source =
				let
				    Source = SupportTables,
				    Custom = Source{1}[Custom],
				    #"Changed Type" = Table.TransformColumnTypes(Custom,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Column1", "Column2"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Other Columns", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Macrofaction", type text}, {"Faction", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

