table 'Force Organisations'
	lineageTag: 4ef12bc4-603f-440e-a561-b21da848f6d1

	column ForceOrgs
		dataType: string
		lineageTag: b17eb7a7-7bae-4932-9292-f377b6ae7d44
		summarizeBy: none
		sourceColumn: ForceOrgs

		annotation SummarizationSetBy = Automatic

	column mechOnly
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 21e6882d-b7db-4300-8999-b29c63fb4646
		summarizeBy: none
		sourceColumn: mechOnly

		annotation SummarizationSetBy = Automatic

	partition 'Force Organisations' = m
		mode: import
		queryGroup: '00 Utilities\00.02 Support Tables\00.02.00 FromGit'
		source =
				let
				    Source = #"supportTables-stg",
				    Data = Source{2}[Data],
				    #"Converted to Table" = Table.FromList(Data, Splitter.SplitTextByDelimiter("~"), null, null, ExtraValues.Error),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Converted to Table", [PromoteAllScalars=true]),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Promoted Headers",{{"ForceOrgs", Text.Proper, type text}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Capitalized Each Word",{{"mechOnly", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

