table 'Force Organisations'
	lineageTag: 4ef12bc4-603f-440e-a561-b21da848f6d1

	column ForceOrgs
		dataType: string
		lineageTag: 52f65f01-2693-4ffe-8544-473e7dbdcb85
		summarizeBy: none
		sourceColumn: ForceOrgs

		annotation SummarizationSetBy = Automatic

	column mechOnly
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ab67f3e2-4a95-406b-9956-84bf7c7ee67e
		summarizeBy: none
		sourceColumn: mechOnly

		annotation SummarizationSetBy = Automatic

	partition 'Force Organisations' = m
		mode: import
		queryGroup: '00 Utilities\00.03 FromGitHub'
		source =
				let
				    Source = SupportTables,
				    Custom = Source{2}[Custom],
				    #"Promoted Headers" = Table.PromoteHeaders(Custom, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ForceOrgs", type text}, {"mechOnly", type logical}, {"", type text}, {"_1", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"ForceOrgs", "mechOnly"})
				in
				    #"Removed Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

