table Subfactions
	lineageTag: 4aa21526-ab3c-4e89-aadb-17aa8aa26e13

	column Subfactions
		dataType: string
		lineageTag: 8982892a-499c-47fb-9510-496fca748f7c
		summarizeBy: none
		sourceColumn: Subfactions

		annotation SummarizationSetBy = Automatic

	column AllowedIn
		dataType: string
		lineageTag: 98a3788c-c27a-4b37-ba1a-a35110d19d03
		summarizeBy: none
		sourceColumn: AllowedIn

		annotation SummarizationSetBy = Automatic

	partition Subfactions = m
		mode: import
		queryGroup: '00 Utilities\00.02 Support Tables'
		source =
				let
				    Source = #"supportTables-stg",
				    Data = Source{5}[Data],
				    #"Split Column by Delimiter" = Table.SplitColumn(Data, "Column1", Splitter.SplitTextByDelimiter("~", QuoteStyle.Csv), {"Column1.1", "Column1.2"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Split Column by Delimiter", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Subfactions", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

