table Subfactions
	lineageTag: 4aa21526-ab3c-4e89-aadb-17aa8aa26e13

	column Subfactions
		dataType: string
		lineageTag: 8982892a-499c-47fb-9510-496fca748f7c
		summarizeBy: none
		sourceColumn: Subfactions

		annotation SummarizationSetBy = Automatic

	column AllowedIn
		dataType: string
		lineageTag: 98a3788c-c27a-4b37-ba1a-a35110d19d03
		summarizeBy: none
		sourceColumn: AllowedIn

		annotation SummarizationSetBy = Automatic

	column ExclusiveTo
		dataType: string
		lineageTag: 111902e4-3963-4c68-916c-b8c453d4ad65
		summarizeBy: none
		sourceColumn: ExclusiveTo

		annotation SummarizationSetBy = Automatic

	partition Subfactions = m
		mode: import
		queryGroup: '00 Utilities\00.02 Support Tables\00.02.00 FromGit'
		source =
				let
				    Source = #"supportTables-stg",
				    Data = Source{5}[Data],
				    #"Converted to Table" = Table.FromList(Data, Splitter.SplitTextByDelimiter("~"), null, null, ExtraValues.Error),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Converted to Table", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Subfactions", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

