table Subfactions
	lineageTag: 4aa21526-ab3c-4e89-aadb-17aa8aa26e13

	column Subfactions
		dataType: string
		lineageTag: 8982892a-499c-47fb-9510-496fca748f7c
		summarizeBy: none
		sourceColumn: Subfactions

		annotation SummarizationSetBy = Automatic

	column AllowedIn
		dataType: string
		lineageTag: 8113eb10-e37d-4ab1-9a22-57cb6eab270c
		summarizeBy: none
		sourceColumn: AllowedIn

		annotation SummarizationSetBy = Automatic

	partition Subfactions = m
		mode: import
		queryGroup: '00 Utilities\00.03 FromGitHub'
		source =
				let
				    Source = SupportTables,
				    Custom = Source{5}[Custom],
				    #"Changed Type" = Table.TransformColumnTypes(Custom,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Column1", "Column2"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Other Columns", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Subfactions", type text}, {"AllowedIn", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

