table 'Warlord Traits'
	lineageTag: 3a53066d-17fa-4231-a10b-c6386b13f3df

	column Faction
		dataType: string
		isHidden
		lineageTag: b7cc3b22-e4c5-4099-81de-9483c82113d6
		summarizeBy: none
		sourceColumn: Faction

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: aab38495-27ff-4400-9653-b181afb388e0
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = User

	column Name
		dataType: string
		lineageTag: 85969730-4527-4790-bb5b-b369b5f9787b
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Effect
		dataType: string
		lineageTag: 9b39d151-2ecf-4c18-a0c6-2223ff0032ea
		summarizeBy: none
		sourceColumn: Effect

		annotation SummarizationSetBy = Automatic

	partition 'Warlord Traits' = m
		mode: import
		queryGroup: '00 Utilities\00.02 Support Tables\00.02.00 FromGit'
		source =
				let
				    Source = #"supportTables-stg",
				    Data = Source{6}[Data],
				    #"Converted to Table" = Table.FromList(Data, Splitter.SplitTextByDelimiter("~"), null, null, ExtraValues.Error),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Converted to Table", [PromoteAllScalars=true]),
				    #"Changed all to types" = Table.TransformColumnTypes(#"Promoted Headers",{{"Faction", type text}, {"Index", Int32.Type}, {"Name", type text}, {"Effect", type text}})
				in
				    #"Changed all to types"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

